export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_UP_FAILED = "USER_SIGN_UP_FAILED";
export const USER_SIGN_UP_SUCCESS="USER_SIGN_UP_SUCCESS"

export const FETCH_ALL_USER = "FETCH_ALL_USER";
export const FETCH_ALL_USER_FAILED = "FETCH_ALL_USER_FAILED";
export const FETCH_ALL_USER_SUCCESS="FETCH_ALL_USER_SUCCESS"


export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";


export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const CLEAR_USER_PROFILE_UPDATE_STATUS = "CLEAR_USER_PROFILE_UPDATE_STATUS";

export const USER_NOT_REGISTERED = "USER_NOT_REGISTERED";
export const USER_DELETED = "USER_DELETED";


